#!/bin/bash

# generated by https://github.com/jeffsanc/auto.git

export my_CUR_FOLDER=$(pwd);
# source ~/$ROS_WS_NAME/install/setup.sh
echo "Going to ROS workspace folder: "$ROS_WS_NAME
cd ~/$ROS_WS_NAME && colcon build --symlink-install;
cd $my_CUR_FOLDER;
echo "Returning back to previous folder:":$my_CUR_FOLDER
